### ISSUE TITLE
Multi channel image

### ISSUE THREAD

**Issue by hadim** [InsightSoftwareConsortium/itk-jupyter-widgets#113] opened 2018-11-26 03:01 UTC
At the moment the viewer can only display a single channel image (unless I missed it). 

Would be nice to display multichannel images where we can set the colormap for each channel and toggle on/off each channel individually. Similar to `Channel Tools` in ImageJ.

**Comment by thewtex** [comment] 2018-11-26 03:15
Yes.

Closing as duplicate of #85

**Closed by thewtex** 2018-11-26 03:15 UTC
